version: '2'
services:
    mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
        #        working_dir: /application
        volumes:
            - ./:/application
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=chinedu
            - MYSQL_DATABASE=smarttrackerdb
            - MYSQL_USER=chinedu
            - MYSQL_PASSWORD=chinedu
        ports:
            - '8082:3306'
    sTracker:
        container_name: sTrackerApp
        image: php:7.3-apache
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
        working_dir: /var/www/html/
        ports:
            - 8000:80
        depends_on:
            - mysql
